// gen-tool-catalog walks the one-user full-access registry and emits
// a machine-readable catalog (JSON) and a human-readable rendering
// (Markdown) for docs/tool-catalog.{json,md}.
//
// Usage:
//
//	go run ./scripts/gen-tool-catalog -out docs
//
// The generator is deterministic: runs from the same code emit
// byte-identical output. CI uses the drift check
//
//	make gen-tool-catalog && git diff --exit-code docs/tool-catalog.*
//
// to refuse PRs that forget to regenerate after adding or changing
// a tool. No network calls, no real Clockify client — the descriptor
// builders only need the Service struct populated with nil fields.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/apet97/go-clockify/internal/mcp"
	"github.com/apet97/go-clockify/internal/tools"
)

// catalogTool is the JSON shape emitted for each tool. Fields match
// MCP's Tool struct plus the ToolDescriptor hints so consumers can
// filter by read/write/destructive without parsing Markdown.
//
// RiskClass and AuditKeys surface the structured taxonomy so
// consumers can filter on billing / admin / permission_change /
// external_side_effect without grep-ing source.
type catalogTool struct {
	Name         string         `json:"name"`
	Description  string         `json:"description,omitempty"`
	Category     string         `json:"category,omitempty"`
	ReadOnly     bool           `json:"read_only"`
	Destructive  bool           `json:"destructive"`
	Idempotent   bool           `json:"idempotent"`
	DryRun       bool           `json:"dry_run"`
	RiskClass    []string       `json:"risk_class,omitempty"`
	AuditKeys    []string       `json:"audit_keys,omitempty"`
	InputSchema  map[string]any `json:"input_schema,omitempty"`
	OutputSchema map[string]any `json:"output_schema,omitempty"`
	Annotations  map[string]any `json:"annotations,omitempty"`
}

func riskClassNames(rc mcp.RiskClass) []string {
	if rc == 0 {
		return nil
	}
	type entry struct {
		bit  mcp.RiskClass
		name string
	}
	all := []entry{
		{mcp.RiskRead, "read"},
		{mcp.RiskWrite, "write"},
		{mcp.RiskBilling, "billing"},
		{mcp.RiskAdmin, "admin"},
		{mcp.RiskPermissionChange, "permission_change"},
		{mcp.RiskExternalSideEffect, "external_side_effect"},
		{mcp.RiskDestructive, "destructive"},
	}
	out := make([]string, 0, 2)
	for _, e := range all {
		if rc.Has(e.bit) {
			out = append(out, e.name)
		}
	}
	return out
}

type catalog struct {
	Generator string        `json:"generator"`
	Tools     []catalogTool `json:"tools"`
}

func main() {
	outDir := flag.String("out", "docs", "output directory for tool-catalog.{json,md}")
	flag.Parse()

	svc := &tools.Service{}
	registry := svc.FullAccessRegistry()

	cat := catalog{
		Generator: "scripts/gen-tool-catalog — DO NOT EDIT BY HAND; run `make gen-tool-catalog` to refresh",
		Tools:     toCatalog(registry),
	}

	if err := writeJSON(filepath.Join(*outDir, "tool-catalog.json"), cat); err != nil {
		log.Fatalf("write json: %v", err)
	}
	if err := writeMarkdown(filepath.Join(*outDir, "tool-catalog.md"), cat); err != nil {
		log.Fatalf("write md: %v", err)
	}
	fmt.Printf("wrote %d tools to %s/tool-catalog.{json,md}\n", len(cat.Tools), *outDir)
}

func toCatalog(ds []mcp.ToolDescriptor) []catalogTool {
	out := make([]catalogTool, 0, len(ds))
	for _, d := range ds {
		category, _ := d.Tool.Annotations["category"].(string)
		out = append(out, catalogTool{
			Name:         d.Tool.Name,
			Description:  d.Tool.Description,
			Category:     category,
			ReadOnly:     d.ReadOnlyHint,
			Destructive:  d.DestructiveHint,
			Idempotent:   d.IdempotentHint,
			DryRun:       annotationBool(d.Tool.Annotations, "dryRun"),
			RiskClass:    riskClassNames(d.RiskClass),
			AuditKeys:    d.AuditKeys,
			InputSchema:  d.Tool.InputSchema,
			OutputSchema: d.Tool.OutputSchema,
			Annotations:  d.Tool.Annotations,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func annotationBool(annotations map[string]any, key string) bool {
	v, _ := annotations[key].(bool)
	return v
}

func writeJSON(path string, v any) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func writeMarkdown(path string, c catalog) error {
	var b strings.Builder
	b.WriteString("# Tool catalog\n\n")
	b.WriteString("Autogenerated by `scripts/gen-tool-catalog`. Do not edit by hand;\n")
	b.WriteString("re-run `make gen-tool-catalog` after changing any tool descriptor.\n\n")
	fmt.Fprintf(&b, "- Tools: **%d** (all registered at startup; workflow tools first, domain tools second, raw API fallback last).\n\n", len(c.Tools))
	writeCookbookLinks(&b)
	writeTimeEntryGuidance(&b)

	b.WriteString("## Tools\n\n")
	writeTable(&b, c.Tools)
	writeAuditKeysSection(&b, c)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeCookbookLinks(b *strings.Builder) {
	b.WriteString("## Agent cookbook recipes\n\n")
	b.WriteString("Intent-keyed examples live in [agent-cookbook.md](agent-cookbook.md):\n\n")
	b.WriteString("| Intent | Primary tools |\n")
	b.WriteString("|--------|---------------|\n")
	b.WriteString("| [Log time for past work](agent-cookbook.md#log-time-for-past-work) | `clockify_log_time`, `clockify_resolve_name` |\n")
	b.WriteString("| [Catch up an empty timesheet for the week](agent-cookbook.md#catch-up-an-empty-timesheet-for-the-week) | `clockify_timesheet_review`, `clockify_timesheet_fill_gap` |\n")
	b.WriteString("| [Fix a wrong project on yesterday's entries](agent-cookbook.md#fix-a-wrong-project-on-yesterdays-entries) | `clockify_list_entries`, `clockify_update_entry` |\n")
	b.WriteString("| [Stop the timer and start a new one](agent-cookbook.md#stop-the-timer-and-start-a-new-one) | `clockify_timer_status`, `clockify_switch_project` |\n")
	b.WriteString("| [Bill a client for last month's hours](agent-cookbook.md#bill-a-client-for-last-months-hours) | `clockify_detailed_report`, `clockify_create_invoice`, `clockify_send_invoice` |\n")
	b.WriteString("| [Subscribe to NEW_TIME_ENTRY events and validate the URL](agent-cookbook.md#subscribe-to-new-time-entry-events-and-validate-the-url) | `clockify_create_webhook`, `clockify_test_webhook` |\n\n")
}

func writeTimeEntryGuidance(b *strings.Builder) {
	b.WriteString("## Time-entry tool choice\n\n")
	b.WriteString("For finished past work, prefer `clockify_log_time`: it requires `start`\n")
	b.WriteString("and `end`, supports `dry_run`, accepts flexible datetime inputs, and\n")
	b.WriteString("checks for overlaps by default. Use `allow_overlap:true` only after a\n")
	b.WriteString("manual review confirms the overlap is intentional.\n\n")
	b.WriteString("Use `clockify_timesheet_review` before catch-up work, then\n")
	b.WriteString("`clockify_timesheet_fill_gap` for approved gaps. Use\n")
	b.WriteString("`clockify_add_entry` only when the lower-level behavior is deliberate,\n")
	b.WriteString("especially omitting `end` to create a running entry. Use\n")
	b.WriteString("`clockify_start_timer` or `clockify_switch_project` for live timers.\n\n")

	b.WriteString("## Time formats\n\n")
	b.WriteString("Time-entry and report range fields accept RFC3339 values and\n")
	b.WriteString("common flexible forms parsed in the requested `timezone`, `CLOCKIFY_TIMEZONE`,\n")
	b.WriteString("or local/server timezone when no timezone is supplied:\n")
	b.WriteString("`YYYY-MM-DD`, `YYYY-MM-DD HH:MM`, `today HH:MM`, `yesterday HH:MM`,\n")
	b.WriteString("and `now`. Fields whose schema still says `RFC3339` only are stricter;\n")
	b.WriteString("prefer the documented format on each tool descriptor.\n\n")
}

func writeAuditKeysSection(b *strings.Builder, c catalog) {
	var rows []catalogTool
	for _, t := range c.Tools {
		if len(t.AuditKeys) > 0 {
			rows = append(rows, t)
		}
	}
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })

	b.WriteString("\n## Audit-tracked argument capture\n\n")
	b.WriteString("Tools below record action-defining arguments alongside the\n")
	b.WriteString("default `*_id` capture in audit events. The per-tool `audit_keys`\n")
	b.WriteString("list also surfaces in `docs/tool-catalog.json`.\n\n")
	b.WriteString("| Tool | Audit Keys |\n")
	b.WriteString("|------|------------|\n")
	for _, r := range rows {
		parts := make([]string, len(r.AuditKeys))
		for i, k := range r.AuditKeys {
			parts[i] = "`" + k + "`"
		}
		fmt.Fprintf(b, "| `%s` | %s |\n", r.Name, strings.Join(parts, ", "))
	}
}

func writeTable(b *strings.Builder, rows []catalogTool) {
	b.WriteString("| Tool | Category | Read-only | Destructive | Idempotent | Dry-run | Risk | Description |\n")
	b.WriteString("|------|----------|-----------|-------------|------------|---------|------|-------------|\n")
	for _, t := range rows {
		desc := strings.ReplaceAll(t.Description, "|", "\\|")
		desc = strings.ReplaceAll(desc, "\n", " ")
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %s | %s | %s |\n",
			t.Name, categoryCell(t.Category), yn(t.ReadOnly), yn(t.Destructive), yn(t.Idempotent), yn(t.DryRun), riskCell(t.RiskClass), desc)
	}
}

func yn(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func categoryCell(c string) string {
	if c == "" {
		return "—"
	}
	return "`" + c + "`"
}

func riskCell(names []string) string {
	if len(names) == 0 {
		return "—"
	}
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = "`" + n + "`"
	}
	return strings.Join(parts, ", ")
}
