package tools

import (
	"testing"
	"time"

	"github.com/apet97/go-clockify/internal/clockify"
)

// TestToolOutputSchema_ActionConstMatchesName is the D4 descriptor-vs-
// runtime contract guard. Every outputSchema generated by
// envelopeSchemaFor or envelopeOpaque pins `action` as a JSON Schema
// const; that const must match the registered tool name. Before D4
// nothing caught a copy-paste drift — a schema that advertised
// action="clockify_whoami" on a tool named "clockify_current_user"
// would silently mis-dispatch strongly-typed clients.
//
// The check runs across every Tier 1 tool and every Tier 2 group's
// full descriptor set. A failure is always "schema author copy-paste"
// or "renamed tool, forgot schemas" — both cheap to fix once the test
// names them.
func TestToolOutputSchema_ActionConstMatchesName(t *testing.T) {
	svc := New(clockify.NewClient("k", "https://api.clockify.me/api/v1", 5*time.Second, 0), "ws1")

	check := func(name string, schema map[string]any) {
		t.Helper()
		if schema == nil {
			return // opt-in; a tool may intentionally omit outputSchema.
		}
		props, _ := schema["properties"].(map[string]any)
		if props == nil {
			t.Errorf("%s: outputSchema has no properties map (got %T)", name, schema["properties"])
			return
		}
		action, _ := props["action"].(map[string]any)
		if action == nil {
			// Not every schema is an envelope. Skip silently so custom
			// shapes opt out gracefully.
			return
		}
		got, hasConst := action["const"]
		if !hasConst {
			return
		}
		if got != name {
			t.Errorf("%s: outputSchema action const = %q, want %q (drift: regenerate the schema or rename the tool)",
				name, got, name)
		}
	}

	for _, d := range svc.Registry() {
		check(d.Tool.Name, d.Tool.OutputSchema)
	}
	for group := range Tier2Groups {
		descriptors, ok := svc.Tier2Handlers(group)
		if !ok {
			t.Fatalf("Tier2Handlers(%q) missing", group)
		}
		for _, d := range descriptors {
			check(d.Tool.Name, d.Tool.OutputSchema)
		}
	}
}

// TestToolDescriptors_AnnotationsMatchHints asserts the three bool
// hints on a descriptor (ReadOnlyHint, DestructiveHint, IdempotentHint)
// are echoed in the tool's Annotations map. TestToolContractMatrix
// already enforces this for Tier 1 via assertBoolAnnotation, but Tier
// 2 was never covered — a Tier 2 group whose descriptors forgot to set
// the annotation map would mislead any MCP client that dispatches off
// annotations.readOnlyHint.
func TestToolDescriptors_AnnotationsMatchHints(t *testing.T) {
	svc := New(clockify.NewClient("k", "https://api.clockify.me/api/v1", 5*time.Second, 0), "ws1")

	check := func(name string, readOnly, destructive, idempotent bool, annotations map[string]any) {
		t.Helper()
		if annotations == nil {
			t.Errorf("%s: annotations map is nil (hints cannot be reflected back to clients)", name)
			return
		}
		assertBoolAnnotation(t, name, annotations, "readOnlyHint", readOnly)
		assertBoolAnnotation(t, name, annotations, "destructiveHint", destructive)
		assertBoolAnnotation(t, name, annotations, "idempotentHint", idempotent)
	}

	for _, d := range svc.Registry() {
		check(d.Tool.Name, d.ReadOnlyHint, d.DestructiveHint, d.IdempotentHint, d.Tool.Annotations)
	}
	for group := range Tier2Groups {
		descriptors, ok := svc.Tier2Handlers(group)
		if !ok {
			t.Fatalf("Tier2Handlers(%q) missing", group)
		}
		for _, d := range descriptors {
			check(d.Tool.Name, d.ReadOnlyHint, d.DestructiveHint, d.IdempotentHint, d.Tool.Annotations)
		}
	}
}
