// Code generated by scripts/gen-raw-allowlist; DO NOT EDIT.

package tools

var documentedWriteRoutes = map[string]bool{
	// approval-requests
	"PATCH /workspaces/{workspaceId}/approval-requests/{approvalRequestId}":                         true,
	"POST /workspaces/{workspaceId}/approval-requests":                                              true,
	"POST /workspaces/{workspaceId}/approval-requests/resubmit-entries-for-approval":                true,
	"POST /workspaces/{workspaceId}/approval-requests/users/{userId}":                               true,
	"POST /workspaces/{workspaceId}/approval-requests/users/{userId}/resubmit-entries-for-approval": true,

	// audit-log
	"POST /workspaces/{workspaceId}/audit-log": true,

	// clients
	"DELETE /workspaces/{workspaceId}/clients/{clientId}":      true,
	"POST /workspaces/{workspaceId}/clients":                   true,
	"PUT /workspaces/{workspaceId}/clients/{clientId}":         true,
	"PUT /workspaces/{workspaceId}/clients/{clientId}/archive": true,

	// cost-rate
	"PUT /workspaces/{workspaceId}/cost-rate": true,

	// custom-fields
	"DELETE /workspaces/{workspaceId}/custom-fields/{customFieldId}": true,
	"POST /workspaces/{workspaceId}/custom-fields":                   true,
	"PUT /workspaces/{workspaceId}/custom-fields/{customFieldId}":    true,

	// expenses
	"DELETE /workspaces/{workspaceId}/expenses/categories/{categoryId}":       true,
	"DELETE /workspaces/{workspaceId}/expenses/{expenseId}":                   true,
	"PATCH /workspaces/{workspaceId}/expenses/categories/{categoryId}/status": true,
	"POST /workspaces/{workspaceId}/expenses":                                 true,
	"POST /workspaces/{workspaceId}/expenses/categories":                      true,
	"PUT /workspaces/{workspaceId}/expenses/categories/{categoryId}":          true,
	"PUT /workspaces/{workspaceId}/expenses/{expenseId}":                      true,

	// holidays
	"DELETE /workspaces/{workspaceId}/holidays/{holidayId}": true,
	"POST /workspaces/{workspaceId}/holidays":               true,
	"PUT /workspaces/{workspaceId}/holidays/{holidayId}":    true,

	// hourly-rate
	"PUT /workspaces/{workspaceId}/hourly-rate": true,

	// invoices
	"DELETE /workspaces/{workspaceId}/invoices/{invoiceId}":                      true,
	"DELETE /workspaces/{workspaceId}/invoices/{invoiceId}/items/{order}":        true,
	"DELETE /workspaces/{workspaceId}/invoices/{invoiceId}/payments/{paymentId}": true,
	"PATCH /workspaces/{workspaceId}/invoices/{invoiceId}/status":                true,
	"POST /workspaces/{workspaceId}/invoices":                                    true,
	"POST /workspaces/{workspaceId}/invoices/info":                               true,
	"POST /workspaces/{workspaceId}/invoices/{invoiceId}/duplicate":              true,
	"POST /workspaces/{workspaceId}/invoices/{invoiceId}/items":                  true,
	"POST /workspaces/{workspaceId}/invoices/{invoiceId}/items/import":           true,
	"POST /workspaces/{workspaceId}/invoices/{invoiceId}/payments":               true,
	"PUT /workspaces/{workspaceId}/invoices/settings":                            true,
	"PUT /workspaces/{workspaceId}/invoices/{invoiceId}":                         true,

	// member-profile
	"PATCH /workspaces/{workspaceId}/member-profile/{userId}": true,
	"PUT /workspaces/{workspaceId}/member-profile/{userId}":   true,

	// policies
	"DELETE /workspaces/{workspaceId}/policies/{policyId}":                      true,
	"DELETE /workspaces/{workspaceId}/policies/{policyId}/requests/{requestId}": true,
	"PATCH /workspaces/{workspaceId}/policies/{policyId}/archive":               true,
	"PATCH /workspaces/{workspaceId}/policies/{policyId}/requests/{requestId}":  true,
	"POST /workspaces/{workspaceId}/policies":                                   true,
	"POST /workspaces/{workspaceId}/policies/{policyId}/requests":               true,
	"PUT /workspaces/{workspaceId}/policies/{policyId}":                         true,

	// projects
	"DELETE /workspaces/{workspaceId}/projects/{projectId}":                               true,
	"DELETE /workspaces/{workspaceId}/projects/{projectId}/custom-fields/{customFieldId}": true,
	"DELETE /workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}":                true,
	"PATCH /workspaces/{workspaceId}/projects/{projectId}/custom-fields/{customFieldId}":  true,
	"PATCH /workspaces/{workspaceId}/projects/{projectId}/estimate":                       true,
	"PATCH /workspaces/{workspaceId}/projects/{projectId}/memberships":                    true,
	"PATCH /workspaces/{workspaceId}/projects/{projectId}/template":                       true,
	"POST /workspaces/{workspaceId}/projects":                                             true,
	"POST /workspaces/{workspaceId}/projects/from-template":                               true,
	"POST /workspaces/{workspaceId}/projects/{projectId}/memberships":                     true,
	"POST /workspaces/{workspaceId}/projects/{projectId}/tasks":                           true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}":                                  true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/archive":                          true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/cost-rate":                        true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/hourly-rate":                      true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}":                   true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/cost-rate":         true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/hourly-rate":       true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/users/{userId}/cost-rate":         true,
	"PUT /workspaces/{workspaceId}/projects/{projectId}/users/{userId}/hourly-rate":       true,

	// reports
	"POST /workspaces/{workspaceId}/reports/attendance":        true,
	"POST /workspaces/{workspaceId}/reports/detailed":          true,
	"POST /workspaces/{workspaceId}/reports/expenses/detailed": true,
	"POST /workspaces/{workspaceId}/reports/summary":           true,
	"POST /workspaces/{workspaceId}/reports/weekly":            true,

	// scheduling
	"DELETE /workspaces/{workspaceId}/scheduling/assignments/recurring/{assignmentId}": true,
	"DELETE /workspaces/{workspaceId}/scheduling/assignments/{assignmentId}":           true,
	"PATCH /workspaces/{workspaceId}/scheduling/assignments/recurring/{assignmentId}":  true,
	"POST /workspaces/{workspaceId}/scheduling/assignments":                            true,
	"POST /workspaces/{workspaceId}/scheduling/assignments/projects/totals":            true,
	"POST /workspaces/{workspaceId}/scheduling/assignments/recurring":                  true,
	"POST /workspaces/{workspaceId}/scheduling/assignments/user-filter/totals":         true,
	"POST /workspaces/{workspaceId}/scheduling/assignments/users/totals":               true,
	"POST /workspaces/{workspaceId}/scheduling/assignments/{assignmentId}/copy":        true,
	"PUT /workspaces/{workspaceId}/scheduling/assignments/publish":                     true,
	"PUT /workspaces/{workspaceId}/scheduling/assignments/recurring/{assignmentId}":    true,
	"PUT /workspaces/{workspaceId}/scheduling/assignments/series/{assignmentId}":       true,
	"PUT /workspaces/{workspaceId}/scheduling/assignments/{assignmentId}":              true,

	// shared-reports
	"DELETE /workspaces/{workspaceId}/shared-reports/{sharedReportId}": true,
	"POST /workspaces/{workspaceId}/shared-reports":                    true,
	"PUT /workspaces/{workspaceId}/shared-reports/{sharedReportId}":    true,

	// tags
	"DELETE /workspaces/{workspaceId}/tags/{tagId}": true,
	"POST /workspaces/{workspaceId}/tags":           true,
	"PUT /workspaces/{workspaceId}/tags/{tagId}":    true,

	// time-entries
	"DELETE /workspaces/{workspaceId}/time-entries/{timeEntryId}": true,
	"PATCH /workspaces/{workspaceId}/time-entries/invoiced":       true,
	"PATCH /workspaces/{workspaceId}/time-entries/invoiced/bulk":  true,
	"POST /workspaces/{workspaceId}/time-entries":                 true,
	"PUT /workspaces/{workspaceId}/time-entries/{timeEntryId}":    true,

	// time-off
	"DELETE /workspaces/{workspaceId}/time-off/policies/{policyId}":                       true,
	"DELETE /workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}":  true,
	"DELETE /workspaces/{workspaceId}/time-off/requests/{requestId}":                      true,
	"PATCH /workspaces/{workspaceId}/time-off/balance/policy/{policyId}":                  true,
	"PATCH /workspaces/{workspaceId}/time-off/policies/{policyId}":                        true,
	"PATCH /workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}":   true,
	"PATCH /workspaces/{workspaceId}/time-off/requests/{requestId}/status":                true,
	"POST /workspaces/{workspaceId}/time-off/policies":                                    true,
	"POST /workspaces/{workspaceId}/time-off/policies/{policyId}/requests":                true,
	"POST /workspaces/{workspaceId}/time-off/policies/{policyId}/users/{userId}/requests": true,
	"POST /workspaces/{workspaceId}/time-off/requests":                                    true,
	"POST /workspaces/{workspaceId}/time-off/requests/users/{userId}":                     true,
	"PUT /workspaces/{workspaceId}/time-off/policies/{policyId}":                          true,

	// user
	"DELETE /workspaces/{workspaceId}/user/{userId}/time-entries":                       true,
	"PATCH /workspaces/{workspaceId}/user/{userId}/time-entries":                        true,
	"PATCH /workspaces/{workspaceId}/user/{userId}/time-entries/stop":                   true,
	"POST /workspaces/{workspaceId}/user/{userId}/time-entries":                         true,
	"POST /workspaces/{workspaceId}/user/{userId}/time-entries/{timeEntryId}/duplicate": true,
	"PUT /workspaces/{workspaceId}/user/{userId}/time-entries":                          true,

	// user-groups
	"DELETE /workspaces/{workspaceId}/user-groups/{groupId}":                true,
	"DELETE /workspaces/{workspaceId}/user-groups/{groupId}/users/{userId}": true,
	"POST /workspaces/{workspaceId}/user-groups":                            true,
	"POST /workspaces/{workspaceId}/user-groups/{groupId}/users":            true,
	"PUT /workspaces/{workspaceId}/user-groups/{groupId}":                   true,

	// users
	"DELETE /workspaces/{workspaceId}/users/{userId}/roles":                           true,
	"POST /workspaces/{workspaceId}/users":                                            true,
	"POST /workspaces/{workspaceId}/users/info":                                       true,
	"POST /workspaces/{workspaceId}/users/{userId}/roles":                             true,
	"PUT /workspaces/{workspaceId}/users/{userId}":                                    true,
	"PUT /workspaces/{workspaceId}/users/{userId}/cost-rate":                          true,
	"PUT /workspaces/{workspaceId}/users/{userId}/custom-field/{customFieldId}/value": true,
	"PUT /workspaces/{workspaceId}/users/{userId}/hourly-rate":                        true,

	// webhooks
	"DELETE /workspaces/{workspaceId}/webhooks/{webhookId}":                 true,
	"PATCH /workspaces/{workspaceId}/webhooks/{webhookId}/generateNewToken": true,
	"PATCH /workspaces/{workspaceId}/webhooks/{webhookId}/token":            true,
	"POST /workspaces/{workspaceId}/webhooks":                               true,
	"POST /workspaces/{workspaceId}/webhooks/{webhookId}/logs":              true,
	"PUT /workspaces/{workspaceId}/webhooks/{webhookId}":                    true,

	// workspaces
	"PUT /workspaces/{workspaceId}": true,
}

var documentedButRawUnsupportedRoutes = map[string]string{
	"POST /file/image": "global file endpoint is outside pinned workspace; use a typed upload tool if added",
	"POST /workspaces": "workspace creation is outside one-user pinned-workspace scope",
}
