package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	raw, err := os.ReadFile("docs/openapi/clockify-openapi.yaml")
	if err != nil {
		log.Fatal(err)
	}
	var doc struct {
		Paths map[string]map[string]any `yaml:"paths"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		log.Fatal(err)
	}
	var routes []string
	for path, ops := range doc.Paths {
		for method := range ops {
			method = strings.ToUpper(method)
			if method == "GET" || !writeMethod(method) {
				continue
			}
			routes = append(routes, method+" "+canonicalPath(path))
		}
	}
	sort.Strings(routes)
	routes = slicesCompact(routes)

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/gen-raw-allowlist; DO NOT EDIT.\n\n")
	b.WriteString("package tools\n\n")
	b.WriteString("var documentedWriteRoutes = map[string]bool{\n")
	for _, route := range routes {
		fmt.Fprintf(&b, "\t%q: true,\n", route)
	}
	b.WriteString("}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("internal/tools/raw_allowlist_gen.go", formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %d documented raw write routes\n", len(routes))
}

func writeMethod(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH", "DELETE":
		return true
	default:
		return false
	}
}

func canonicalPath(path string) string {
	path = strings.TrimSpace(path)
	path = strings.ReplaceAll(path, "{workspace_id}", "{workspaceId}")
	path = strings.ReplaceAll(path, "{workspaceID}", "{workspaceId}")
	parts := strings.Split(path, "/")
	for i := 0; i+1 < len(parts); i++ {
		if parts[i] == "workspaces" && strings.HasPrefix(parts[i+1], "{") && strings.HasSuffix(parts[i+1], "}") {
			parts[i+1] = "{workspaceId}"
			break
		}
	}
	return strings.Join(parts, "/")
}

func slicesCompact(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := in[:1]
	for _, value := range in[1:] {
		if value != out[len(out)-1] {
			out = append(out, value)
		}
	}
	return out
}
