package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	raw, err := os.ReadFile("docs/openapi/clockify-openapi.yaml")
	if err != nil {
		log.Fatal(err)
	}
	var doc struct {
		Paths map[string]map[string]any `yaml:"paths"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		log.Fatal(err)
	}
	var routes []string
	unsupported := map[string]string{}
	for path, ops := range doc.Paths {
		for method := range ops {
			method = strings.ToUpper(method)
			if method == "GET" || !writeMethod(method) {
				continue
			}
			route := method + " " + canonicalPath(path)
			if rawWriteRouteSupported(route) {
				routes = append(routes, route)
			} else {
				unsupported[route] = rawUnsupportedReason(route)
			}
		}
	}
	sort.Strings(routes)
	routes = slicesCompact(routes)

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/gen-raw-allowlist; DO NOT EDIT.\n\n")
	b.WriteString("package tools\n\n")
	b.WriteString("var documentedWriteRoutes = map[string]bool{\n")
	grouped := map[string][]string{}
	for _, route := range routes {
		section := routeSection(route)
		grouped[section] = append(grouped[section], route)
	}
	sections := make([]string, 0, len(grouped))
	for section := range grouped {
		sections = append(sections, section)
	}
	sort.Strings(sections)
	for i, section := range sections {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "\t// %s\n", section)
		for _, route := range grouped[section] {
			fmt.Fprintf(&b, "\t%q: true,\n", route)
		}
	}
	b.WriteString("}\n")
	if len(unsupported) > 0 {
		b.WriteString("\nvar documentedButRawUnsupportedRoutes = map[string]string{\n")
		unsupportedRoutes := make([]string, 0, len(unsupported))
		for route := range unsupported {
			unsupportedRoutes = append(unsupportedRoutes, route)
		}
		sort.Strings(unsupportedRoutes)
		for _, route := range unsupportedRoutes {
			fmt.Fprintf(&b, "\t%q: %q,\n", route, unsupported[route])
		}
		b.WriteString("}\n")
	}
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("internal/tools/raw_allowlist_gen.go", formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %d documented raw write routes (%d unsupported by raw scope)\n", len(routes), len(unsupported))
}

func writeMethod(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH", "DELETE":
		return true
	default:
		return false
	}
}

func canonicalPath(path string) string {
	path = strings.TrimSpace(path)
	path = strings.ReplaceAll(path, "{workspace_id}", "{workspaceId}")
	path = strings.ReplaceAll(path, "{workspaceID}", "{workspaceId}")
	parts := strings.Split(path, "/")
	for i := 0; i+1 < len(parts); i++ {
		if parts[i] == "workspaces" && strings.HasPrefix(parts[i+1], "{") && strings.HasSuffix(parts[i+1], "}") {
			parts[i+1] = "{workspaceId}"
			break
		}
	}
	return strings.Join(parts, "/")
}

func rawWriteRouteSupported(route string) bool {
	_, path, ok := strings.Cut(route, " ")
	if !ok {
		return false
	}
	path = strings.ReplaceAll(path, "{workspaceId}", "ws-test")
	return path == "/workspaces/ws-test" || strings.HasPrefix(path, "/workspaces/ws-test/")
}

func rawUnsupportedReason(route string) string {
	_, path, _ := strings.Cut(route, " ")
	switch path {
	case "/file/image":
		return "global file endpoint is outside pinned workspace; use a typed upload tool if added"
	case "/workspaces":
		return "workspace creation is outside one-user pinned-workspace scope"
	default:
		return "route is outside the one-user pinned-workspace raw fallback scope"
	}
}

// routeSection returns the API section a "METHOD /path" route belongs to: the
// path segment after {workspaceId}, or the first segment for non-workspace
// routes. It groups the generated allowlist for human review.
func routeSection(route string) string {
	parts := strings.SplitN(route, " ", 2)
	if len(parts) != 2 {
		return "other"
	}
	segments := strings.Split(strings.Trim(parts[1], "/"), "/")
	for i, seg := range segments {
		if seg == "{workspaceId}" && i+1 < len(segments) {
			return segments[i+1]
		}
	}
	if len(segments) > 0 && segments[0] != "" {
		return segments[0]
	}
	return "other"
}

func slicesCompact(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := in[:1]
	for _, value := range in[1:] {
		if value != out[len(out)-1] {
			out = append(out, value)
		}
	}
	return out
}
