package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/apet97/go-clockify/internal/config"
)

var groupOrder = []string{
	"Core",
	"Safety",
	"Performance",
	"Bootstrap",
	"Transport",
	"Auth",
	"Metrics",
	"ControlPlane",
	"Audit",
	"Logging",
	"Deploy",
	"Misc",
}

// RenderHelp produces the grouped text block that clockify-mcp --help prints.
// Output layout: "Environment Variables:\n" + one block per group. Entries
// within a group are alphabetised by Name so adding a new var at the end of
// AllSpecs() does not shuffle help output unpredictably.
func RenderHelp(specs []config.EnvSpec) string {
	groups := map[string][]config.EnvSpec{}
	for _, s := range specs {
		g := s.Group
		if g == "" {
			g = "Misc"
		}
		groups[g] = append(groups[g], s)
	}
	var buf bytes.Buffer
	buf.WriteString("Environment Variables:\n")
	for _, g := range groupOrder {
		items, ok := groups[g]
		if !ok {
			continue
		}
		sort.Slice(items, func(i, j int) bool { return items[i].Name < items[j].Name })
		fmt.Fprintf(&buf, "\n  %s:\n", g)
		for _, s := range items {
			buf.WriteString(formatHelpLine(s))
			buf.WriteByte('\n')
		}
	}
	return buf.String()
}

func formatHelpLine(s config.EnvSpec) string {
	var suffix []string
	if s.Default != "" {
		suffix = append(suffix, "default: "+s.Default)
	}
	if len(s.Enum) > 0 {
		suffix = append(suffix, strings.Join(s.Enum, "|"))
	}
	if len(s.AppliesTo) > 0 {
		suffix = append(suffix, "transports: "+strings.Join(s.AppliesTo, ","))
	}
	if s.Deprecated {
		suffix = append(suffix, "DEPRECATED — use "+s.Replacement)
	}
	help := s.Help
	if len(suffix) > 0 {
		help = strings.TrimSpace(help + " [" + strings.Join(suffix, "; ") + "]")
	}
	return fmt.Sprintf("    %-38s %s", s.Name, help)
}

// renderHelpGo wraps the plain help text in a Go source file so the binary
// can embed the generated content directly. The file is regenerated whenever
// AllSpecs() changes; the config-doc-parity gate enforces it.
func renderHelpGo(specs []config.EnvSpec) string {
	return fmt.Sprintf(`// Code generated by cmd/gen-config-docs. DO NOT EDIT.
// Regenerate with: go run ./cmd/gen-config-docs -mode=all

package main

const generatedHelp = %q
`, RenderHelp(specs))
}

// RenderREADMETable emits the bounded markdown block for README.md
// essentials. Sorted by Name for reviewer-friendly diffs.
func RenderREADMETable(specs []config.EnvSpec) string {
	sorted := make([]config.EnvSpec, 0, len(specs))
	for _, s := range specs {
		if s.EssentialDoc {
			sorted = append(sorted, s)
		}
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var buf bytes.Buffer
	buf.WriteString(readmeBeginMarker)
	buf.WriteString(" — generated by cmd/gen-config-docs; do not edit by hand -->\n")
	buf.WriteString("| Variable | Default | Purpose |\n")
	buf.WriteString("|----------|---------|---------|\n")
	for _, s := range sorted {
		def := s.Default
		if def == "" {
			def = "—"
		}
		help := s.Help
		if s.Deprecated {
			help = "**Deprecated — use `" + s.Replacement + "`.** " + help
		}
		fmt.Fprintf(&buf, "| `%s` | `%s` | %s |\n", s.Name, def, help)
	}
	buf.WriteString(readmeEndMarker)
	buf.WriteString("\n")
	return buf.String()
}
